### ISSUE TITLE
Background Geolocation "leaks" ServiceConection when application is closed by user.

### ISSUE THREAD

**Issue by SteveLamont** [kamgolabek/Flutter_Background_Geolocation_Plugin#2]
When closing an application using background_geolocation_plugin, I get the following traceback:
```1E/ActivityThread(24658): Activity org.tirebiter.tracker.MainActivity has leaked ServiceConnection com.kgit.background_geolocation_plugin.service.MeasureManager$1@7e2ac53 that was originally bound here
E/ActivityThread(24658): android.app.ServiceConnectionLeaked: Activity org.tirebiter.tracker.MainActivity has leaked ServiceConnection com.kgit.background_geolocation_plugin.service.MeasureManager$1@7e2ac53 that was originally bound here
E/ActivityThread(24658): 	at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1811)
E/ActivityThread(24658): 	at android.app.LoadedApk.getServiceDispatcherCommon(LoadedApk.java:1683)
E/ActivityThread(24658): 	at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:1662)
E/ActivityThread(24658): 	at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1819)
E/ActivityThread(24658): 	at android.app.ContextImpl.bindService(ContextImpl.java:1749)
E/ActivityThread(24658): 	at android.content.ContextWrapper.bindService(ContextWrapper.java:756)
E/ActivityThread(24658): 	at com.kgit.background_geolocation_plugin.service.MeasureManager.bindToService(MeasureManager.java:188)
E/ActivityThread(24658): 	at com.kgit.background_geolocation_plugin.service.MeasureManager.startBackgroundLocationService(MeasureManager.java:264)
E/ActivityThread(24658): 	at com.kgit.background_geolocation_plugin.service.MeasureManager.activate(MeasureManager.java:226)
E/ActivityThread(24658): 	at com.kgit.background_geolocation_plugin.service.MeasureManager.startMeasure(MeasureManager.java:105)
E/ActivityThread(24658): 	at com.kgit.background_geolocation_plugin.BackgroundGeolocationPlugin.onMethodCall(BackgroundGeolocationPlugin.java:67)
E/ActivityThread(24658): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/ActivityThread(24658): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/ActivityThread(24658): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/ActivityThread(24658): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/ActivityThread(24658): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/ActivityThread(24658): 	at android.os.Looper.loop(Looper.java:183)
E/ActivityThread(24658): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/ActivityThread(24658): 	at java.lang.reflect.Method.invoke(Native Method)
E/ActivityThread(24658): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/ActivityThread(24658): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```
This appears to be because when the Activity is detached, `MeasureManager` is not stopped.

Adding `_measureManager.stopMeasure();` to `onDetachedFromActivity` in `BackgroundGeolocationPlugin` as follows seems to cure the issue:
```  @Override
  public void onDetachedFromActivity() {
    System.out.println("onDetachedFromActivity");
    try {
        _measureManager.stopMeasure();
    } catch ( Exception e ) {

        System.out.println("onDetachedFromActivity exception " + e );

    }

    _activity = null;
  }
```
There may or may not be a better way of handling a potential exception, of course, but my Java-fu is somewhat rusty these days and I'll leave that to wiser heads than mine to elaborate.

**Comment by SteveLamont** [comment]
Just checking back in to see if this issue will be addressed soon.  It seems like it should be an easy fix to me, but, as always, I may be missing something.
